

export const candidateData = [
    {
        id: 1,
        soDienThoai: "0912345678",
        avatar: "",
        nguonUngVien: "Facebook",
        hoTen: "Nguyễn Văn An",
        email: "an.nguyen@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q4/2025",
        viTriTuyenDung: "Frontend Developer",
        tinTuyenDung: "JD Frontend React",
        vongTuyenDung: "Phỏng vấn kỹ thuật",
        danhGia: 4,
        ngayUngTuyen: "15/12/2025",

        trinhDoDaoTao: "Đại học",
        noiDaoTao: "ĐH Bách Khoa Hà Nội",
        chuyenNganh: "Công nghệ thông tin",

        noiLamViec: "Hà Nội",
        nhanSuKhaiThac: "Đinh Nga QTHT",
        donViSuDung: "Phòng CNTT",
        phuHopChanDung: true,
        khuVuc: "Miền Bắc",
        nguoiGioiThieu: "",
        thongTinTiepNhan: "Ứng viên tự ứng tuyển",
        thuocKhoTiemNang: true,
        createdAt: "2025-12-15T08:30:00Z",
        updatedAt: ""
    },
    {
        id: 2,
        soDienThoai: "0987654321",
        avatar: "",
        nguonUngVien: "Website",
        hoTen: "Trần Thị Bình",
        email: "binh.tran@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q4/2025",
        viTriTuyenDung: "Backend Developer",
        tinTuyenDung: "JD Backend Java",
        vongTuyenDung: "Sàng lọc CV",
        danhGia: 3,
        ngayUngTuyen: "14/12/2025",

        trinhDoDaoTao: "Đại học",
        noiDaoTao: "ĐH Công Nghệ",
        chuyenNganh: "Kỹ thuật phần mềm",

        noiLamViec: "Hà Nội",
        nhanSuKhaiThac: "Nguyễn Văn HR",
        donViSuDung: "Phòng Backend",
        phuHopChanDung: false,
        khuVuc: "Miền Bắc",
        nguoiGioiThieu: "Lê Văn C",
        thongTinTiepNhan: "Giới thiệu nội bộ",
        thuocKhoTiemNang: false,
        createdAt: "2025-12-14T10:15:00Z",
        updatedAt: ""
    },
    {
        id: 3,
        soDienThoai: "0901234567",
        avatar: "",
        nguonUngVien: "LinkedIn",
        hoTen: "Phạm Quốc Cường",
        email: "cuong.pham@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q1/2026",
        viTriTuyenDung: "Data Engineer",
        tinTuyenDung: "JD Data Engineer",
        vongTuyenDung: "Phỏng vấn HR",
        danhGia: 5,
        ngayUngTuyen: "13/12/2025",

        trinhDoDaoTao: "Thạc sĩ",
        noiDaoTao: "ĐH Quốc Gia Hà Nội",
        chuyenNganh: "Khoa học dữ liệu",

        noiLamViec: "Hà Nội",
        nhanSuKhaiThac: "Trần Thu HR",
        donViSuDung: "Phòng Data",
        phuHopChanDung: true,
        khuVuc: "Miền Bắc",
        nguoiGioiThieu: "",
        thongTinTiepNhan: "LinkedIn Apply",
        thuocKhoTiemNang: true,
        createdAt: "2025-12-13T09:00:00Z",
        updatedAt: ""
    },
    {
        id: 4,
        soDienThoai: "0978123456",
        avatar: "",
        nguonUngVien: "Referral",
        hoTen: "Lê Minh Dũng",
        email: "dung.le@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q4/2025",
        viTriTuyenDung: "UI/UX Designer",
        tinTuyenDung: "JD UI/UX",
        vongTuyenDung: "Offer",
        danhGia: 5,
        ngayUngTuyen: "12/12/2025",

        trinhDoDaoTao: "Đại học",
        noiDaoTao: "ĐH Mỹ Thuật",
        chuyenNganh: "Thiết kế đồ họa",

        noiLamViec: "TP Hồ Chí Minh",
        nhanSuKhaiThac: "Hoàng Anh HR",
        donViSuDung: "Phòng Design",
        phuHopChanDung: true,
        khuVuc: "Miền Nam",
        nguoiGioiThieu: "Nguyễn Văn E",
        thongTinTiepNhan: "Giới thiệu nội bộ",
        thuocKhoTiemNang: false,
        createdAt: "2025-12-12T11:45:00Z",
        updatedAt: ""
    },
    {
        id: 5,
        soDienThoai: "0934567890",
        avatar: "",
        nguonUngVien: "Facebook",
        hoTen: "Vũ Thị Hạnh",
        email: "hanh.vu@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q1/2026",
        viTriTuyenDung: "QA Engineer",
        tinTuyenDung: "JD QA Manual",
        vongTuyenDung: "Test kỹ thuật",
        danhGia: 4,
        ngayUngTuyen: "11/12/2025",

        trinhDoDaoTao: "Cao đẳng",
        noiDaoTao: "CĐ CNTT",
        chuyenNganh: "Kiểm thử phần mềm",

        noiLamViec: "Đà Nẵng",
        nhanSuKhaiThac: "Lê Hồng HR",
        donViSuDung: "Phòng QA",
        phuHopChanDung: true,
        khuVuc: "Miền Trung",
        nguoiGioiThieu: "",
        thongTinTiepNhan: "Ứng viên tự ứng tuyển",
        thuocKhoTiemNang: true,
        createdAt: "2025-12-11T14:20:00Z",
        updatedAt: ""
    },
    {
        id: 6,
        soDienThoai: "0966543210",
        avatar: "",
        nguonUngVien: "Website",
        hoTen: "Đỗ Văn Khánh",
        email: "khanh.do@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q4/2025",
        viTriTuyenDung: "DevOps Engineer",
        tinTuyenDung: "JD DevOps",
        vongTuyenDung: "Phỏng vấn kỹ thuật",
        danhGia: 5,
        ngayUngTuyen: "10/12/2025",

        trinhDoDaoTao: "Đại học",
        noiDaoTao: "ĐH FPT",
        chuyenNganh: "Hệ thống thông tin",

        noiLamViec: "Hà Nội",
        nhanSuKhaiThac: "Nguyễn Thị HR",
        donViSuDung: "Phòng DevOps",
        phuHopChanDung: true,
        khuVuc: "Miền Bắc",
        nguoiGioiThieu: "",
        thongTinTiepNhan: "Website Apply",
        thuocKhoTiemNang: false,
        createdAt: "2025-12-10T16:00:00Z",
        updatedAt: ""
    },
    {
        id: 7,
        soDienThoai: "0922334455",
        avatar: "",
        nguonUngVien: "LinkedIn",
        hoTen: "Hoàng Gia Long",
        email: "long.hoang@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q1/2026",
        viTriTuyenDung: "Product Owner",
        tinTuyenDung: "JD PO",
        vongTuyenDung: "Phỏng vấn CEO",
        danhGia: 5,
        ngayUngTuyen: "09/12/2025",

        trinhDoDaoTao: "Thạc sĩ",
        noiDaoTao: "ĐH Kinh Tế Quốc Dân",
        chuyenNganh: "Quản trị kinh doanh",

        noiLamViec: "Hà Nội",
        nhanSuKhaiThac: "Trần Minh HR",
        donViSuDung: "Phòng Sản phẩm",
        phuHopChanDung: true,
        khuVuc: "Miền Bắc",
        nguoiGioiThieu: "",
        thongTinTiepNhan: "LinkedIn Recruiter",
        thuocKhoTiemNang: false,
        createdAt: "2025-12-09T09:30:00Z",
        updatedAt: ""
    },
    {
        id: 8,
        soDienThoai: "0945566778",
        avatar: "",
        nguonUngVien: "Referral",
        hoTen: "Nguyễn Thị Mai",
        email: "mai.nguyen@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q4/2025",
        viTriTuyenDung: "HR Executive",
        tinTuyenDung: "JD HR",
        vongTuyenDung: "Phỏng vấn HR",
        danhGia: 4,
        ngayUngTuyen: "08/12/2025",

        trinhDoDaoTao: "Đại học",
        noiDaoTao: "ĐH Lao động Xã hội",
        chuyenNganh: "Quản trị nhân sự",

        noiLamViec: "TP Hồ Chí Minh",
        nhanSuKhaiThac: "Phạm Thu HR",
        donViSuDung: "Phòng Nhân sự",
        phuHopChanDung: true,
        khuVuc: "Miền Nam",
        nguoiGioiThieu: "Trần Văn H",
        thongTinTiepNhan: "Giới thiệu nội bộ",
        thuocKhoTiemNang: true,
        createdAt: "2025-12-08T13:10:00Z",
        updatedAt: ""
    },
    {
        id: 9,
        soDienThoai: "0956677889",
        avatar: "",
        nguonUngVien: "Facebook",
        hoTen: "Bùi Văn Nam",
        email: "nam.bui@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q1/2026",
        viTriTuyenDung: "Mobile Developer",
        tinTuyenDung: "JD Flutter",
        vongTuyenDung: "Test kỹ thuật",
        danhGia: 3,
        ngayUngTuyen: "07/12/2025",

        trinhDoDaoTao: "Đại học",
        noiDaoTao: "ĐH Giao Thông",
        chuyenNganh: "CNTT",

        noiLamViec: "Hải Phòng",
        nhanSuKhaiThac: "Nguyễn Văn HR",
        donViSuDung: "Phòng Mobile",
        phuHopChanDung: false,
        khuVuc: "Miền Bắc",
        nguoiGioiThieu: "",
        thongTinTiepNhan: "Facebook Apply",
        thuocKhoTiemNang: true,
        createdAt: "2025-12-07T15:45:00Z",
        updatedAt: ""
    },
    {
        id: 10,
        soDienThoai: "0979988776",
        avatar: "",
        nguonUngVien: "Website",
        hoTen: "Ngô Thị Phương",
        email: "phuong.ngo@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q4/2025",
        viTriTuyenDung: "Marketing Executive",
        tinTuyenDung: "JD Marketing",
        vongTuyenDung: "Phỏng vấn HR",
        danhGia: 4,
        ngayUngTuyen: "06/12/2025",

        trinhDoDaoTao: "Đại học",
        noiDaoTao: "ĐH Thương Mại",
        chuyenNganh: "Marketing",

        noiLamViec: "Hà Nội",
        nhanSuKhaiThac: "Lê Anh HR",
        donViSuDung: "Phòng Marketing",
        phuHopChanDung: true,
        khuVuc: "Miền Bắc",
        nguoiGioiThieu: "",
        thongTinTiepNhan: "Website Apply",
        thuocKhoTiemNang: false,
        createdAt: "2025-12-06T10:00:00Z",
        updatedAt: ""
    },
    {
        id: 11,
        soDienThoai: "0987654321",
        avatar: "",
        nguonUngVien: "LinkedIn",
        hoTen: "Trần Văn An",
        email: "an.tran@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q4/2025",
        viTriTuyenDung: "Software Engineer",
        tinTuyenDung: "JD Software Engineer",
        vongTuyenDung: "Phỏng vấn Technical",
        danhGia: 5,
        ngayUngTuyen: "07/12/2025",
        trinhDoDaoTao: "Đại học",
        noiDaoTao: "ĐH Bách Khoa",
        chuyenNganh: "Công nghệ thông tin",
        noiLamViec: "Hà Nội",
        nhanSuKhaiThac: "Nguyễn Minh HR",
        donViSuDung: "Phòng IT",
        phuHopChanDung: true,
        khuVuc: "Miền Bắc",
        nguoiGioiThieu: "",
        thongTinTiepNhan: "LinkedIn Apply",
        thuocKhoTiemNang: false,
        createdAt: "2025-12-07T09:30:00Z",
        updatedAt: ""
    },
    {
        id: 12,
        soDienThoai: "0912345678",
        avatar: "",
        nguonUngVien: "Website",
        hoTen: "Lê Thị Bích",
        email: "bich.le@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q4/2025",
        viTriTuyenDung: "Graphic Designer",
        tinTuyenDung: "JD Designer",
        vongTuyenDung: "Phỏng vấn HR",
        danhGia: 3,
        ngayUngTuyen: "08/12/2025",
        trinhDoDaoTao: "Cao đẳng",
        noiDaoTao: "CĐ Mỹ thuật",
        chuyenNganh: "Thiết kế đồ họa",
        noiLamViec: "Hà Nội",
        nhanSuKhaiThac: "Lê Anh HR",
        donViSuDung: "Phòng Marketing",
        phuHopChanDung: true,
        khuVuc: "Miền Bắc",
        nguoiGioiThieu: "",
        thongTinTiepNhan: "Website Apply",
        thuocKhoTiemNang: false,
        createdAt: "2025-12-08T14:20:00Z",
        updatedAt: ""
    },
    {
        id: 13,
        soDienThoai: "0909876543",
        avatar: "",
        nguonUngVien: "Facebook",
        hoTen: "Nguyễn Văn Cường",
        email: "cuong.nguyen@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q4/2025",
        viTriTuyenDung: "Sales Executive",
        tinTuyenDung: "JD Sales",
        vongTuyenDung: "Phỏng vấn Manager",
        danhGia: 4,
        ngayUngTuyen: "09/12/2025",
        trinhDoDaoTao: "Đại học",
        noiDaoTao: "ĐH Kinh tế Quốc dân",
        chuyenNganh: "Quản trị kinh doanh",
        noiLamViec: "Hà Nội",
        nhanSuKhaiThac: "Nguyễn Minh HR",
        donViSuDung: "Phòng Sales",
        phuHopChanDung: true,
        khuVuc: "Miền Bắc",
        nguoiGioiThieu: "",
        thongTinTiepNhan: "Facebook Apply",
        thuocKhoTiemNang: false,
        createdAt: "2025-12-09T11:15:00Z",
        updatedAt: ""
    },
    {
        id: 14,
        soDienThoai: "0934567890",
        avatar: "",
        nguonUngVien: "Referral",
        hoTen: "Phạm Thị Dung",
        email: "dung.pham@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q4/2025",
        viTriTuyenDung: "HR Specialist",
        tinTuyenDung: "JD HR",
        vongTuyenDung: "Phỏng vấn HR",
        danhGia: 5,
        ngayUngTuyen: "10/12/2025",
        trinhDoDaoTao: "Đại học",
        noiDaoTao: "ĐH Lao động Xã hội",
        chuyenNganh: "Quản trị nhân sự",
        noiLamViec: "Hà Nội",
        nhanSuKhaiThac: "Lê Anh HR",
        donViSuDung: "Phòng HR",
        phuHopChanDung: true,
        khuVuc: "Miền Bắc",
        nguoiGioiThieu: "Nguyễn Văn B",
        thongTinTiepNhan: "Referral",
        thuocKhoTiemNang: true,
        createdAt: "2025-12-10T08:45:00Z",
        updatedAt: ""
    },
    {
        id: 15,
        soDienThoai: "0923456789",
        avatar: "",
        nguonUngVien: "Website",
        hoTen: "Đặng Văn Hùng",
        email: "hung.dang@gmail.com",
        chienDichTuyenDung: "Tuyển dụng Q4/2025",
        viTriTuyenDung: "Marketing Executive",
        tinTuyenDung: "JD Marketing",
        vongTuyenDung: "Phỏng vấn HR",
        danhGia: 4,
        ngayUngTuyen: "11/12/2025",
        trinhDoDaoTao: "Đại học",
        noiDaoTao: "ĐH Thương Mại",
        chuyenNganh: "Marketing",
        noiLamViec: "Hà Nội",
        nhanSuKhaiThac: "Lê Anh HR",
        donViSuDung: "Phòng Marketing",
        phuHopChanDung: true,
        khuVuc: "Miền Bắc",
        nguoiGioiThieu: "",
        thongTinTiepNhan: "Website Apply",
        thuocKhoTiemNang: false,
        createdAt: "2025-12-11T10:30:00Z",
        updatedAt: ""
    }

];

const existingData = localStorage.getItem("candidateList");
if (!existingData) {
    localStorage.setItem("candidateList", JSON.stringify(candidateData));
}